# Generated by Django 4.0.1 on 2022-01-21 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='start_point_lat',
            new_name='start_point_late',
        ),
    ]
