# Generated by Django 4.0.1 on 2022-01-21 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_start_point_lat_order_start_point_late'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='end_point_late',
            new_name='end_point_lat',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='start_point_late',
            new_name='start_point_lat',
        ),
    ]
